version: '3'
services:
  mosquitto-prod:
    image: krosand/mosquitto-wazuh:latest
    container_name: mosquitto-prod
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    environment:
      - WAZUH_MANAGER='172.18.0.4'
      - WAZUH_AGENT_GROUP='default'
      - WAZUH_AGENT_NAME='mosquitto'
    volumes:
      - /mnt/containers/mosquitto/config:/mosquitto/config
      - /mnt/containers/mosquitto/data:/mosquitto/data
      - /mnt/containers/mosquitto/log:/mosquitto/log
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
    networks:
      - single-node_default

networks:
  single-node_default:
    external: true
