version: '3.8'

services:
  mosquitto-wazuh:
    image: krosand/mosquitto-wazuh:latest
    environment:
      - WAZUH_MANAGER=${WAZUH_MANAGER}
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    restart: unless-stopped
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_config:/mosquitto/config

volumes:
  mosquitto_data:
  mosquitto_config:
networks:
  reverseproxy-nw:
    external: true
