name: Test and Deploy Main Branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image for Main
        uses: docker/build-push-action@v2
        with:
          context: ./mosquitto
          file: ./mosquitto/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mosquitto-wazuh:latest

      - name: Deploy to Production Environment
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/mosquitto-wazuh:latest
          docker run -d --name mosquitto-wazuh-prod -e WAZUH_MANAGER='172.18.0.2' -p 1883:1883 ${{ secrets.DOCKER_USERNAME }}/mosquitto-wazuh:latest

